# -*- coding: utf-8 -*-
"""Unemployment Analysis Task 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14II1WKD52PpWD6uIgTPXhfIQKui0xrYc

# **OASIS INFOBYTE INTERNSHIP, TASK 2**

# NAME: ANIRUDHA CHAKRABORTY
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

data = pd.read_csv("/content/Unemployment in India.csv")
data = pd.read_csv("/content/Unemployment_Rate_upto_11_2020.csv")
print(data.head())

print(data.isnull().sum())

data.columns= ["States","Date","Frequency","Estimated Employment Rate","Estimated Employed","Estimated Labour Participation Rate","Region", "longitude","latitude"]

#CORRELATION

plt.style.use('seaborn-whitegrid')
plt.figure(figsize=(12,10))
sns.heatmap(data.corr())
plt.show()

# Data Vizualization 

data.columns =["States","Dates","Frequency","Estimated Unemployment Rate","Estimated Employed","Estimated Labour Participation Rate","Region","longitude","latitude"]
plt.title("Indian Unemployement")
sns.histplot(x="Estimated Employed",hue="Region",data=data)
plt.show()

# See the unemployment rate according to different region of India
plt.figure(figsize=(12,10))
plt.title("Indian Unemployment")
sns.histplot(x="Estimated Unemployment Rate",hue="Region",data=data)
plt.show()

# See the unemployment rate according to different region of India
plt.figure(figsize=(12,10))
plt.title("Indian Unemployment")
sns.histplot(x="Estimated Unemployment Rate",hue="Region",data=data)
plt.show()

# Create a dashboard to analyze the unemployment rate of each Indian state by region .use sunburst plot.
unemployment = data[["States","Region","Estimated Unemployment Rate"]]
figure = px.sunburst(unemployment,path=["Region","States"], values="Estimated Unemployment Rate", width =700,height =700, color_continuous_scale="RdY2Gn",title="Unemployement Rate in Indian")
figure.show()